config/routes.rb
Rails.application.routes.draw do
  resources :seq_range_troop_numbers
  resources :types
  resources :drivers
  resources :range_troop_numbers
  resources :product_details
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'welcome/index'

  resources :agents
  resources :animal_types
  resources :animals
  resources :cities
  resources :troop_details
  resources :troops
  resources :places
  resources :positions
  resources :providers
  resources :production_details
  resources :productions
  resources :sub_product_details
  resources :sub_product_types
  resources :sub_products
  resources :transports
  resources :turn_details
  resources :turns
  devise_for :users

  post '/sub_product/edit_with_details' => 'sub_products#edit_with_details'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  
  get 'production_line/' => 'static_pages#production_line'

  get 'troops/new_troop_ajax' => 'troops#new_troop_ajax', :as => :new_troop_ajax

end

app/models/transport.rb
class Transport < ApplicationRecord
	validates :coupled, :presence => true
	validates :capacity, :presence => true
	validates :plate, :presence => true
	validates :weight, :presence => true
	def to_s
		model+" "+plate
	end
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /transports
  # GET /transports.json
  def index
    @transports = Transport.all
  end

  # GET /transports/1
  # GET /transports/1.json
  def show
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports
  # POST /transports.json
  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to @transport, notice: 'Transporte exitosamente creado.' }
        format.json { render :show, status: :created, location: @transport }
      else
        format.html { render :new }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1
  # PATCH/PUT /transports/1.json
  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to @transport, notice: 'Transporte exitosamente actualizado.' }
        format.json { render :show, status: :ok, location: @transport }
      else
        format.html { render :edit }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1
  # DELETE /transports/1.json
  def destroy
    @transport.destroy
    respond_to do |format|
      format.html { redirect_to transports_url, notice: 'Transporte exitosamente borrado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transport_params
      params.require(:transport).permit(:coupled, :capacity, :plate, :model, :driver, :weight, :brand)
    end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.erb
 
<%= form_for(transport) do |f| %>
  <% if transport.errors.any? %>
    <script type="text/javascript">
      <% transport.errors.full_messages.each do |message| %>
        toastr['error']('<%= message %>');
      <% end %>
    </script>
  <% end %>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Acoplado:
  </label>
  <div class="col-sm-12 col-md-9 controls">
        <%= f.text_field :coupled, class: "form-control input-lg", placeholder: "Acoplado"%>
        <span class="help-block">Obligatorio. </span>
  </div>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Capacidad:
  </label>
  <div class="col-sm-12 col-md-9 controls">
        <%= f.number_field :capacity, class: "form-control input-lg", placeholder: "Capacidad"%>
        <span class="help-block">Obligatorio. </span>
  </div>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Patente:
  </label>
  <div class="col-sm-12 col-md-9 controls">
        <%= f.text_field :plate, class: "form-control input-lg", placeholder: "Patente"%>
        <span class="help-block">Obligatorio. </span>
  </div>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Modelo:
  </label>
  <div class="col-sm-12 col-md-9 controls">
        <%= f.number_field :model, class: "form-control input-lg", placeholder: "Modelo"%>
  </div>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Peso:
  </label>
  <div class="col-sm-12 col-md-9 controls">
        <%= f.text_field :weight, class: "form-control input-lg", placeholder: "Peso"%>
        <span class="help-block">Obligatorio. </span>
  </div>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Marca:
  </label>
  <div class="col-sm-12 col-md-9 controls">
        <%= f.text_field :brand, class: "form-control input-lg", placeholder: "Marca"%>
  </div>

  <div class="col-xs-4">
    <%= link_to 'Volver', transports_path, class: "btn btn-primary btn-block" %>
  </div>      
  <div class="col-xs-8">
    <%= f.submit class: "btn btn-success btn-block"%>
  </div>  
<% end %>

app/views/transports/edit.html.erb
<div class="col-md-10 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Editar Transporte</h2>
</div>

<div class="col-md-8 col-xs-12">
	<%= render 'form', transport: @transport %>
</div>

<!--%= link_to 'Mostrar', @agent %> |
<%= link_to 'Volver', agents_path %>

app/views/transports/index.html.erb
<div class="col-md-10  col-xs-12">
  <h2>Transportes</h2>
</div>

<div class="col-md-10  col-xs-12">
  <table class="datatable table-striped table-bordered table-list">
    <thead>
      <tr>
        <th>Acoplado</th>
        <th>Capacidad</th>
        <th>Patente</th>
        <th>Modelo</th>
        <th>Peso</th>
        <th>Marca</th>
        <th>Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @transports.each do |transport| %>
        <tr>
          <td><%= transport.coupled %></td>
          <td><%= transport.capacity %></td>
          <td><%= transport.plate %></td>
          <td><%= transport.model %></td>
          <td><%= transport.weight %></td>
          <td><%= transport.brand %></td>
          <td>
            <%= link_to (fa_icon "eye"), transport, class: '' %>
            <%= link_to (fa_icon "pencil-square-o"), edit_transport_path(transport), class: '' %>
            <%= link_to (fa_icon "trash-o"), transport, method: :delete, data: { confirm: '¿Seguro desea eliminar este registro?' }, class: '' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="col-md-10  col-xs-12">
  <%= link_to 'Nuevo Transporte', new_transport_path, {:class=>"btn btn-primary btn-submit"} %>
</div>

app/views/transports/new.html.erb
<div class="col-md-8 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Nuevo Transporte</h2>
</div>
<div class="col-md-8 col-xs-12">
	<%= render 'form', transport: @transport %>
</div>

app/views/transports/show.html.erb
<div class="col-xs-12">
  <h2 style="text-align: center;">Transporte</h2>
</div>

<label class="col-xs-3 control-label">
  Acoplado:
</label>
<div class="col-xs-9 show-field">
  <%= @transport.coupled %>
</div>

<label class="col-xs-3 control-label">
  Capacidad:
</label>
<div class="col-xs-9 show-field">
  <%= @transport.capacity %>
</div>

<label class="col-xs-3 control-label">
  Patente:
</label>
<div class="col-xs-9 show-field">
  <%= @transport.plate %>
</div>

<label class="col-xs-3 control-label">
  Modelo:
</label>
<div class="col-xs-9 show-field">
  <%= @transport.model %>
</div>

<label class="col-xs-3 control-label">
  Peso:
</label>
<div class="col-xs-9 show-field">
  <%= @transport.weight %>
</div>

<label class="col-xs-3 control-label">
  Marca:
</label>
<div class="col-xs-9 show-field">
  <%= @transport.brand %>
</div>

<div class="col-xs-4">
  <%= link_to 'Editar', edit_transport_path(@transport), class: "btn btn-primary btn-block" %>
</div>      
<div class="col-xs-8">
  <%= link_to 'Volver', transports_path, class: "btn btn-success btn-block"%>
</div> 