config/routes.rb
Rails.application.routes.draw do
  resources :seq_range_troop_numbers
  resources :types
  resources :drivers
  resources :range_troop_numbers
  resources :product_details
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'welcome/index'

  resources :agents
  resources :animal_types
  resources :animals
  resources :cities
  resources :troop_details
  resources :troops
  resources :places
  resources :positions
  resources :providers
  resources :production_details
  resources :productions
  resources :sub_product_details
  resources :sub_product_types
  resources :sub_products
  resources :transports
  resources :turn_details
  resources :turns
  devise_for :users

  post '/sub_product/edit_with_details' => 'sub_products#edit_with_details'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  
  get 'production_line/' => 'static_pages#production_line'

  get 'troops/new_troop_ajax' => 'troops#new_troop_ajax', :as => :new_troop_ajax

end

app/models/seq_range_troop_number.rb
class SeqRangeTroopNumber < ApplicationRecord
end

app/controllers/seq_range_troop_numbers_controller.rb
class SeqRangeTroopNumbersController < ApplicationController
  before_action :set_seq_range_troop_number, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /seq_range_troop_numbers
  # GET /seq_range_troop_numbers.json
  def index
    @seq_range_troop_numbers = SeqRangeTroopNumber.all
  end

  # GET /seq_range_troop_numbers/1
  # GET /seq_range_troop_numbers/1.json
  def show
  end

  # GET /seq_range_troop_numbers/new
  def new
    @seq_range_troop_number = SeqRangeTroopNumber.new
  end

  # GET /seq_range_troop_numbers/1/edit
  def edit
  end

  # POST /seq_range_troop_numbers
  # POST /seq_range_troop_numbers.json
  def create
    @seq_range_troop_number = SeqRangeTroopNumber.new(seq_range_troop_number_params)

    respond_to do |format|
      if @seq_range_troop_number.save
        format.html { redirect_to @seq_range_troop_number, notice: 'Seq range troop number was successfully created.' }
        format.json { render :show, status: :created, location: @seq_range_troop_number }
      else
        format.html { render :new }
        format.json { render json: @seq_range_troop_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seq_range_troop_numbers/1
  # PATCH/PUT /seq_range_troop_numbers/1.json
  def update
    respond_to do |format|
      if @seq_range_troop_number.update(seq_range_troop_number_params)
        format.html { redirect_to @seq_range_troop_number, notice: 'Seq range troop number was successfully updated.' }
        format.json { render :show, status: :ok, location: @seq_range_troop_number }
      else
        format.html { render :edit }
        format.json { render json: @seq_range_troop_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seq_range_troop_numbers/1
  # DELETE /seq_range_troop_numbers/1.json
  def destroy
    @seq_range_troop_number.destroy
    respond_to do |format|
      format.html { redirect_to seq_range_troop_numbers_url, notice: 'Seq range troop number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seq_range_troop_number
      @seq_range_troop_number = SeqRangeTroopNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seq_range_troop_number_params
      params.require(:seq_range_troop_number).permit(:rtn)
    end
end

app/helpers/seq_range_troop_numbers_helper.rb
module SeqRangeTroopNumbersHelper
end

app/views/seq_range_troop_numbers/_form.html.erb
<%= form_for(seq_range_troop_number) do |f| %>
  <% if seq_range_troop_number.errors.any? %>
    <script type="text/javascript">
      <% seq_range_troop_number.errors.full_messages.each do |message| %>
        toastr['error']('<%= message %>');
      <% end %>
    </script>
  <% end %>
  
  <label class="col-md-3 control-label hidden-sm hidden-xs">
    R.N.T:
  </label>
  <div class="col-sm-12 col-md-9 controls">
      <%= f.number_field :rtn, class: "form-control input-lg", placeholder: "Rango Numero Tropa"%>
      <span class="help-block">Obligatorio. </span>
  </div>
  <div class="col-xs-4">
    <%= link_to 'Volver', seq_range_troop_numbers_path, class: "btn btn-primary btn-block" %>
  </div>      
  <div class="col-xs-8">
    <%= f.submit class: "btn btn-success btn-block"%>
  </div>  
<% end %>

app/views/seq_range_troop_numbers/edit.html.erb
<div class="col-md-10 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Editar RAngo numero de tropa:</h2>
</div>

<div class="col-md-8 col-xs-12">
	<%= render 'form', seq_range_troop_number: @seq_range_troop_number %>
</div>

app/views/seq_range_troop_numbers/index.html.erb
<div class="col-md-10  col-xs-12">
  <h2>Rango Numero tropa</h2>
</div>

<div class="col-md-10  col-xs-12">
  <table class="datatable table-striped table-bordered table-list">
    <thead>
      <tr>
        <th>R.N.T</th>
        <th>Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @seq_range_troop_numbers.each do |seq_range_troop_number| %>
        <tr>
          <td><%= seq_range_troop_number.rtn %></td>
          <td>
            <%= link_to (fa_icon "eye"), seq_range_troop_number, class: '' %>
            <%= link_to (fa_icon "pencil-square-o"), edit_seq_range_troop_number_path(seq_range_troop_number), class: '' %>
            <%= link_to (fa_icon "trash-o"), seq_range_troop_number, method: :delete, data: { confirm: '¿Seguro desea eliminar este registro?' }, class: '' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="col-md-10  col-xs-12">
  <%= link_to 'Crear Rango Numero Tropa', new_seq_range_troop_number_path, {:class=>"btn btn-primary btn-submit"} %>
</div>

app/views/seq_range_troop_numbers/new.html.erb
<div class="col-md-8 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Nuevo Rango Numero Tropa</h2>
</div>
<div class="col-md-8 col-xs-12">
	<%= render 'form', seq_range_troop_number: @seq_range_troop_number %>
</div>

app/views/seq_range_troop_numbers/show.html.erb
<div class="col-xs-12">
  <h2 style="text-align: center;">Rango Numero Tropa</h2>
</div>

<label class="col-xs-3 control-label">
	R.N.T
</label>
<div class="col-xs-9 show-field">
  <%= @seq_range_troop_number.rtn %>
</div>

<div class="col-xs-4">
	<%= link_to 'Editar', edit_seq_range_troop_number_path(@seq_range_troop_number), class: "btn btn-primary btn-block" %>
</div>      
<div class="col-xs-8">
	<%= link_to 'Volver', seq_range_troop_numbers_path, class: "btn btn-success btn-block"%>
</div> 