config/routes.rb
Rails.application.routes.draw do
  resources :seq_range_troop_numbers
  resources :types
  resources :drivers
  resources :range_troop_numbers
  resources :product_details
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'welcome/index'

  resources :agents
  resources :animal_types
  resources :animals
  resources :cities
  resources :troop_details
  resources :troops
  resources :places
  resources :positions
  resources :providers
  resources :production_details
  resources :productions
  resources :sub_product_details
  resources :sub_product_types
  resources :sub_products
  resources :transports
  resources :turn_details
  resources :turns
  devise_for :users

  post '/sub_product/edit_with_details' => 'sub_products#edit_with_details'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  
  get 'production_line/' => 'static_pages#production_line'

  get 'troops/new_troop_ajax' => 'troops#new_troop_ajax', :as => :new_troop_ajax

end

app/models/turn.rb
class Turn < ApplicationRecord

  has_many :turn_details, inverse_of: :turn
  accepts_nested_attributes_for :turn_details, :reject_if => proc { |attributes| attributes['agent_id'].blank? }
  validates_associated :turn_details


  validates :date, :presence => true

  def to_s
    date.to_s + " "+description.to_s
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /turns
  # GET /turns.json
  def index
    @turns = Turn.all
  end

  # GET /turns/1
  # GET /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    @turn = Turn.new
    3.times { @turn.turn_details.build }
  end

  # GET /turns/1/edit
  def edit
    @turn = Turn.find(params[:id])
  end

  # Post 
  def edit_with_details
   
  end

  # POST /turns
  # POST /turns.json
  def create
    @turn = Turn.new(turn_params)

    respond_to do |format|
      if @turn.save
        format.html { redirect_to @turn, notice: 'Turno exitosamente creado.' }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1
  # PATCH/PUT /turns/1.json
  def update
    @turn = Turn.find(params[:id])
    respond_to do |format|
      if @turn.update(turn_params)
        format.html { redirect_to @turn, notice: 'Turno exitosamente actualizado.' }
        format.json { render :show, status: :ok, location: @turn }
      else
        format.html { render :edit }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turns/1
  # DELETE /turns/1.json
  def destroy
    @turn.destroy
    respond_to do |format|
      format.html { redirect_to turns_url, notice: 'Turno exitosamente borrado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turn_params
      params.require(:turn).permit(:date, :description, turn_details_attributes: [:id, :agent_id, :place_id, :position_id, :observation, :_destroy])
    end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= form_for turn,  id:"new_turn" do |f| %>
  <% if turn.errors.any? %>
    <script type="text/javascript">
      <% turn.errors.full_messages.each do |message| %>
        toastr['error']('<%= message %>');
      <% end %>
    </script>
  <% end %>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Fecha:
  </label>  
  <div class="col-sm-12 col-md-9 controls date datepicker">
    <div class="form-group">
      <div class='input-group date'>
        <%= f.text_field :date, placeholder: "Fecha", class: "form-control" %>
        <span class="input-group-addon ">
          <%= fa_icon "list"%>
        </span>
      </div>
      <span class="help-block">Obligatorio.</span>
    </div>
  </div>

  <label class="col-md-3 control-label hidden-sm hidden-xs">
    Descripción:
  </label>
  <div class="col-sm-12 col-md-9 controls">
    <%= f.text_area :description, class: "form-control input-lg", placeholder: "Descripción"%>
    
  </div>
  
  <div class="col-sm-12">
    <h3 style="text-align: center;">Detalle de Agentes del Turno</h3>
  </div>
  
  <div class="col-sm-12" style="margin-bottom: 25px;">
    <table class="table" style="margin-bottom: 0px;">
      <thead>
          <tr>
            <th>Agente</th>
            <th>Lugar</th>
            <th>Posicion</th>
            <th>Observacion</th>
          </tr> 
      </thead>
      <tbody class="turn_details">
            <%= f.fields_for :turn_details do |td| %>
              <%= render 'turn_detail_fields', :f => td %>
            <% end %>
      </tbody>
    </table>
    <%= link_to_add_association (fa_icon "plus"), f, :turn_details, data: { association_insertion_node: '.turn_details', association_insertion_method: :append }, class: "btn btn-primary btn-block" %>
  </div>
  
  
  <div class="col-xs-4">
    <%= link_to 'Volver', turns_path, class: "btn btn-primary btn-block" %>
  </div>      
  <div class="col-xs-4">
    <%= f.submit class: "btn btn-success btn-block"%>
  </div>  
<% end %>

<script type="text/javascript">
  $('form').bind('cocoon:after-insert',
    function(e) {
      console.log("entro");
      $(".select2").select2({theme: "bootstrap", width: "100%"});
      
    });
</script>

app/views/turns/_turn_detail_fields.html.erb
<tr class="nested-field">
	<td><%= f.collection_select :agent_id, Agent.all, :id, :to_s, {prompt: "Agente"}, {class: "select2 form-control input-lg"} %></td>
	<td><%= f.collection_select :place_id, Place.all, :id, :to_s, {prompt: "Lugar"}, {class: "select2 form-control input-lg"} %></td>
	<td><%= f.collection_select :position_id, Position.all, :id, :to_s, {prompt: "Posicion"}, {class: "select2 form-control input-lg"} %></td>
	<td><%= f.text_field :observation, class: "form-control input-lg", placeholder: "Observacion"%></td>
</tr>

app/views/turns/edit.html.erb
<div class="col-md-10 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Editar Turno</h2>
</div>

<div class="col-md-8 col-xs-12">
	<%= render 'form', turn: @turn %>
</div>

app/views/turns/index.html.erb
<div class="col-md-10  col-xs-12">
  <h2>Turnos</h2>
</div>


<div class="col-md-10  col-xs-12">

  <table class="datatable table-striped table-bordered table-list">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Descripcion</th>
        <th>Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @turns.each do |turn| %>
        <tr>
          <td><%= turn.date %></td>
          <td><%= turn.description %></td>
          <td>
            <%= link_to (fa_icon "eye"), turn, class: '' %>
            <%= link_to (fa_icon "pencil-square-o"), edit_turn_path(turn), class: '' %>
            <%= link_to (fa_icon "trash-o"), turn, method: :delete, data: { confirm: '¿Seguro desea eliminar este turno?' }, class: '' %>
                
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col-md-10  col-xs-12">
  <%= link_to 'Crear Turno', new_turn_path, {:class=>"btn btn-primary btn-submit"} %>
</div>

app/views/turns/new.html.erb
<div class="col-md-8 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Nuevo Turno</h2>
</div>
<div class="col-md-8 col-xs-12">
	<%= render 'form', turn: @turn %>
</div>

app/views/turns/show.html.erb
<div class="col-xs-12">
  <h2 style="text-align: center;">Turno</h2>
</div>

<label class="col-xs-3 control-label">
  Fecha:
</label>
<div class="col-xs-9 show-field">
  <%= @turn.date %>
</div>


<label class="col-xs-3 control-label">
  Descripcion:
</label>
<div class="col-xs-9 show-field">
  <%= @turn.description %>
</div>

<div class="col-xs-10  col-xs-12">
    <table class="datatable table-striped table-bordered table-list">
        <thead>
            <tr>
            <th>Agente</th>
            <th>Lugar</th>
            <th>Posicion</th>
            <th>Observacion</th>
            </tr> 
        </thead>
        <tbody>
        <% for details in @turn.turn_details %>
            <tr>
                <td><%= details.agent %></td>
                <td><%= details.place %></td>
                <td><%= details.position %></td>
                <td><%= details.observation %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
<label class="col-xs-3 control-label">
</label>
<div class="col-xs-9 show-field">
</div>


<div class="col-xs-4">
    <%= link_to 'Editar', edit_turn_path(@turn), class: "btn btn-primary btn-block" %>
</div>
<div class="col-xs-8">
    <%= link_to 'Volver', turns_path , class: "btn btn-success btn-block"%>
</div>