config/routes.rb
Rails.application.routes.draw do
  resources :seq_range_troop_numbers
  resources :types
  resources :drivers
  resources :range_troop_numbers
  resources :product_details
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'welcome/index'

  resources :agents
  resources :animal_types
  resources :animals
  resources :cities
  resources :troop_details
  resources :troops
  resources :places
  resources :positions
  resources :providers
  resources :production_details
  resources :productions
  resources :sub_product_details
  resources :sub_product_types
  resources :sub_products
  resources :transports
  resources :turn_details
  resources :turns
  devise_for :users

  post '/sub_product/edit_with_details' => 'sub_products#edit_with_details'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  
  get 'production_line/' => 'static_pages#production_line'

  get 'troops/new_troop_ajax' => 'troops#new_troop_ajax', :as => :new_troop_ajax

end

app/models/sub_product.rb
class SubProduct < ApplicationRecord
  has_many :sub_product_details, inverse_of: :sub_product
  accepts_nested_attributes_for :sub_product_details, reject_if: :all_blank, allow_destroy: true
  belongs_to :troop

  
end

app/models/sub_product_type.rb
class SubProductType < ApplicationRecord
  def to_s
    description
  end
end

app/controllers/sub_products_controller.rb
class SubProductsController < ApplicationController
  before_action :set_sub_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /sub_products
  # GET /sub_products.json
  def index
    @sub_products = SubProduct.all
  end

  # GET /sub_products/1
  # GET /sub_products/1.json
  def show
  end

  # GET /sub_products/new
  def new
    @sub_product = SubProduct.new
    
  end

  # GET /sub_products/1/edit
  def edit
    
  end

  # Post 
  def edit_with_details
   
  end

  # POST /sub_products
  # POST /sub_products.json
  def create

    @sub_product = SubProduct.new(sub_product_params)

    respond_to do |format|
      if @sub_product.save
        format.html { redirect_to @sub_product, notice: 'Sub producto exitosamente creado.' }
        format.json { render :show, status: :created, location: @sub_product }
      else
        format.html { render :new }
        format.json { render json: @sub_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_products/1
  # PATCH/PUT /sub_products/1.json
  def update
    respond_to do |format|
      if @sub_product.update(sub_product_params)
        format.html { redirect_to @sub_product, notice: 'Sub producto exitosamente actualizado.' }
        format.json { render :show, status: :ok, location: @sub_product }
      else
        format.html { render :edit }
        format.json { render json: @sub_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_products/1
  # DELETE /sub_products/1.json
  def destroy
    @sub_product.destroy
    respond_to do |format|
      format.html { redirect_to sub_products_url, notice: 'Sub producto exitosamente borrado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_product
      @sub_product = SubProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_product_params
      params.require(:sub_product).permit(:troop_id, :observartion)

      params.require(:sub_product).permit(:troop_id, :observartion, sub_product_details_attributes: [:id, :sub_product_type_id, :weight, :green, :processed, :red, :caliber, :observartion])
    end
end

app/helpers/sub_products_helper.rb
module SubProductsHelper
end

app/views/sub_products/_form.html.erb
<%= form_for(sub_product) do |f| %>
    <% if sub_product.errors.any? %>
        <script type="text/javascript">
          <% sub_product.errors.full_messages.each do |message| %>
            toastr['error']('<%= message %>');
          <% end %>
        </script>
    <% end %>
  
    <label class="col-md-3 control-label hidden-sm hidden-xs">
        Tropa:
    </label>
    <div class="col-sm-12 col-md-9 controls">
        <%= f.collection_select :troop_id, Troop.where(close_code: ""), :id, :to_s, {prompt: "Tropa"}, {class: "select2", style:""} %>
    </div>

    <label class="col-md-3 control-label hidden-sm hidden-xs">
        Observación:
    </label>
    <div class="col-sm-12 col-md-9 controls">
        <%= f.text_field :observartion, class: "form-control input-lg", placeholder: "Observación"%>
    </div>
    

    <div class="col-sm-12">
        <h3 style="text-align: center;">Detalle de Sub producto</h3>
    </div>

    <div class="col-sm-12" style="margin-bottom: 25px;">
        <table class="table" style="margin-bottom: 0px;">
            <thead>
                <tr>
                    <th>Tipo</th>
                    <% if current_user.SubA?  or current_user.admin?%>
                        <th>Peso</th>
                    <% end %>
                    <% if current_user.SubB?  or current_user.admin?%>
                        <th>Peso control</th>
                    <% end %>
                    <th>Calibre</th>
                    <th>Observacion</th>
                </tr> 
            </thead>
            <tbody class="sub_product_details">
                <%= f.fields_for :sub_product_details do |sub_product_details| %>
                    <%= render 'sub_product_detail_fields', :f => sub_product_details %>
                <% end %>
                </div>
            </tbody>
        </table>
        <div class='links'>
            <%= link_to_add_association (fa_icon "plus"), f, :sub_product_details, data: { association_insertion_node: '.sub_product_details', association_insertion_method: :append }, class: "btn btn-primary btn-block" %>
        </div>
    </div>
    
    <div class="col-xs-4">
        <%= link_to 'Volver', sub_products_path, class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-xs-8">
        <%= f.submit class: "btn btn-success btn-block"%>
    </div>
<% end %>
<script type="text/javascript">
  $('form').bind('cocoon:after-insert',
    function(e) {
      $(".select2").select2({theme: "bootstrap", width: "100%"});
    });
</script>

app/views/sub_products/_sub_product_detail_fields.html.erb
<tr class="nested-field">
	<td><%= f.collection_select :sub_product_type_id, SubProductType.all, :id, :to_s, {prompt: "Tipo"}, {class: "select2", id: "select_sub_product"} %></td>
	<% if current_user.SubA?  or current_user.admin?%>
		<td><%= f.number_field :weight, class: "number_field_detail form-control input-lg", placeholder: ""%></td>
	<% end %>
	<% if current_user.SubB?  or current_user.admin?%>
		<td><%= f.number_field :weight_control, class: "number_field_detail form-control input-lg", placeholder: ""%></td>
	<% end %>
	<td><%= f.number_field :caliber, class: "number_field_detail form-control input-lg", placeholder: "Calibre"%></td>
	<td><%= f.text_field :observartion, class: "form-control input-lg", placeholder: "Observacion"%></td>
</tr>

app/views/sub_products/edit.html.erb
<div class="col-md-10 col-xs-12">
  <h2 style="text-align: center;margin-bottom: 25px;">Edición Sub Producto</h2>
</div>

<div class="col-md-10 col-xs-12">
	<%= render 'form', sub_product: @sub_product %>
</div>

app/views/sub_products/index.html.erb
<div class="col-md-10  col-xs-12">
    <h2>Sub Productos</h2>
</div>

<div class="col-md-10  col-xs-12">
    <table class="datatable table-striped table-bordered table-list">
        <thead>
            <tr>
                <th>Tropa</th>
                <th>Observacion</th>
                <th>Opciones</th>
            </tr>
        </thead>

        <tbody>
            <% @sub_products.each do |sub_product| %>
            <tr>
                <td><%= sub_product.troop %></td>
                <td><%= sub_product.observartion %></td>
                <td>
                <%= link_to (fa_icon "eye"), sub_product, class: '' %>
                <%= link_to (fa_icon "pencil-square-o"), edit_sub_product_path(sub_product), class: '' %>
                <%= link_to (fa_icon "trash-o"), sub_product, method: :delete, data: { confirm: '¿Seguro desea eliminar este registro?' }, class: '' %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<br>

<div class="col-md-10  col-xs-12">
    <% if current_user.SubA?  or current_user.admin?%>
        <%= link_to 'Nuevo Sub Producto', new_sub_product_path , {:class=>"btn btn-primary btn-submit"} %>
    <% end %>
</div>

app/views/sub_products/new.html.erb
<div class="col-md-8 col-xs-12">
    <h2 style="text-align: center;margin-bottom: 25px;">Nuevo Sub Producto</h2>
</div>
<div class="col-md-8 col-xs-12">
    <%= render 'form', sub_product: @sub_product %>
</div>

app/views/sub_products/show.html.erb
<div class="col-xs-12">
  <h2 style="text-align: center;">Sub Producto</h2>
</div>

<label class="col-xs-3 control-label">
    Tropa
</label>
<div class="col-xs-9 show-field">
  <%= @sub_product.troop.dte %>
</div>

<label class="col-xs-3 control-label">
    Observacion:
</label>
<div class="col-xs-9 show-field">
  <%= @sub_product.observartion %>
</div>

<div class="col-xs-10  col-xs-12">
    <table class="datatable table-striped table-bordered table-list">
        <thead>
            <tr>
            <th>Tipo</th>
            <th>Peso</th>
            <th>Peso Procesado</th>
            <th>Calibre</th>
            <th>Observacion</th>
            </tr> 
        </thead>
        <tbody>
        <% for details in @sub_product.sub_product_details %>
            <tr>
                <td><%= details.sub_product_type %></td>
                <td><%= details.weight %></td>
                <td><%= details.weight_control %></td>
                <td><%= details.caliber %></td>
                <td><%= details.observartion %></td>
            </tr>
        <% end %>
        </tbody>
        <tfoot>
            <tr>
                <th>Subtotales</th>
                <th><%= @sub_product.sub_product_details.sum('weight') %></th>
                <th><%= @sub_product.sub_product_details.sum('weight_control') %></th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>

<div class="col-xs-4">
    <%= link_to 'Editar', edit_sub_product_path(@sub_product), class: "btn btn-primary btn-block" %>
</div>
<div class="col-xs-8">
    <%= link_to 'Volver', sub_products_path , class: "btn btn-success btn-block"%>
</div>